document.getElementById('generate').addEventListener('click', function () {
    const excuses = [
        "Meu pet ficou doente.",
        "Houve um apagão na minha rua.",
        "Perdi meu transporte e o próximo demorou muito.",
        "Estava me sentindo indisposto(a).",
        "Tive uma emergência familiar.",
        "Meu alarme não despertou.",
        "Fiquei preso(a) no trânsito.",
        "Meu alarme não tocou.",
        "Fiquei preso no trânsito terrível.",
        "Tive uma emergência familiar.",
        "Perdi a noção do tempo completamente.",
        "Meu pet ficou doente de repente.",
        "Tive que levar alguém ao hospital às pressas.",
        "Meu carro quebrou no caminho.",
        "Acordei me sentindo muito mal.",
        "Tive uma consulta médica que demorou mais do que o esperado.",
        "Recebi uma entrega importante e não podia deixar minha casa.",
        "Meu vizinho teve uma crise e precisei ajudar.",
        "A energia acabou em minha casa na hora de sair.",
        "Perdi meus óculos e não conseguia encontrar outro par.",
        "Tive uma reação alérgica severa.",
        "Fui convocado para uma reunião de última hora.",
        "Meu telefone morreu e perdi meu alarme.",
        "Fiquei preso no elevador.",
        "A chave do meu carro quebrou na fechadura.",
        "Tive que esperar o encanador/electricista/chaveiro.",
        "Meu filho/pai/mãe precisou de mim de última hora.",
        "Fiquei sem gasolina a caminho.",
        "Tive um problema sério de encanamento em casa.",
        "Minha internet estava fora e não consegui enviar uma notificação.",
        "Tive uma dor de cabeça/migrânea incapacitante.",
        "Meu voo foi cancelado/delayed.",
        "Fiquei retido por causa do mau tempo.",
        "Minha bagagem foi perdida durante a viagem.",
        "Tive um problema legal de última hora para resolver.",
        "Meu computador teve um vírus e perdi meu trabalho.",
        "Fui selecionado para o júri de última hora.",
        "Perdi a carteira e tive que lidar com isso.",
        "Meu animal de estimação escapou e tive que procurá-lo.",
        "Recebi uma ligação importante que não podia ignorar.",
        "Acordei com o carro bloqueado por outro veículo.",
        "Tive que acompanhar um amigo ao pronto-socorro.",
        "Meu cartão de crédito foi clonado e tive que resolver o problema.",
        "Percebi que tinha deixado algo essencial em casa.",
        "Fui parado pela polícia no caminho.",
        "Um parente distante apareceu sem avisar.",
        "Tive que lidar com uma infestação de pragas em casa.",
        "A água foi cortada em minha área e tive que resolver.",
        "Fui mordido por um animal e precisei de tratamento.",
        "Perdi o ônibus/trem e o próximo demorou muito a chegar.",
        "Minha mala foi roubada enquanto eu estava a caminho.",
        "Fui testemunha de um acidente e tive que prestar depoimento.",
        "Um amigo em crise me ligou precisando de ajuda.",
        "Tive uma reunião de última hora com um cliente importante.",
        "Meu voo de conexão foi adiado.",
        "Uma tempestade severa me impediu de sair de casa.",
        "Fui afetado por uma interrupção de serviço de transporte público.",
        "Tive um problema de saúde súbito e sério.",
        "Um incidente de segurança me impediu de deixar meu local atual.",
        "Tive que ajudar um vizinho em uma emergência.",
        "Minha casa foi invadida e tive que lidar com a polícia.",
        "Recebi notícias de última hora que me afetaram profundamente.",
        "Tive um problema com a reserva do hotel e precisei resolver.",
        "Fui atingido por uma doença alimentar súbita.",
        "Perdi o passaporte/documento importante e tive que procurá-lo.",
        "Uma manifestação bloqueou meu caminho usual.",
        "Tive uma crise de ansiedade/depressão e não consegui sair.",
        "Um evento inesperado no trabalho me manteve lá."
    ];

    const randomIndex = Math.floor(Math.random() * excuses.length);
    document.getElementById('excuse').textContent = excuses[randomIndex];
});
